# Form implementation generated from reading ui file 'project1Gym.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox

class Ui_gymGlobal(object):
    def setupUi(self, gymGlobal):
        gymGlobal.setObjectName("gymGlobal")
        gymGlobal.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        gymGlobal.setFont(font)
        gymGlobal.setAutoFillBackground(False)
        gymGlobal.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=gymGlobal)
        self.centralwidget.setObjectName("centralwidget")
        self.gymTitle = QtWidgets.QLabel(parent=self.centralwidget)
        self.gymTitle.setGeometry(QtCore.QRect(340, 80, 102, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(17)
        self.gymTitle.setFont(font)
        self.gymTitle.setObjectName("gymTitle")
        self.lblYoga = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblYoga.setGeometry(QtCore.QRect(280, 150, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lblYoga.setFont(font)
        self.lblYoga.setObjectName("lblYoga")
        self.lblRock = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblRock.setGeometry(QtCore.QRect(240, 180, 171, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lblRock.setFont(font)
        self.lblRock.setObjectName("lblRock")
        self.lblPilates = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblPilates.setGeometry(QtCore.QRect(271, 210, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lblPilates.setFont(font)
        self.lblPilates.setObjectName("lblPilates")
        self.lblTime = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTime.setGeometry(QtCore.QRect(355, 240, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lblTime.setFont(font)
        self.lblTime.setObjectName("lblTime")
        self.txtYogaClasses = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtYogaClasses.setGeometry(QtCore.QRect(410, 150, 113, 21))
        self.txtYogaClasses.setObjectName("txtYogaClasses")
        self.txtRockClasses = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtRockClasses.setGeometry(QtCore.QRect(410, 180, 113, 21))
        self.txtRockClasses.setObjectName("txtRockClasses")
        self.txtPilatesClasses = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtPilatesClasses.setGeometry(QtCore.QRect(410, 210, 113, 21))
        self.txtPilatesClasses.setObjectName("txtPilatesClasses")
        self.txtTimeslot = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtTimeslot.setGeometry(QtCore.QRect(410, 240, 113, 21))
        self.txtTimeslot.setObjectName("txtTimeslot")
        self.lblYogaCost = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblYogaCost.setGeometry(QtCore.QRect(530, 150, 51, 16))
        self.lblYogaCost.setObjectName("lblYogaCost")
        self.lblRockCost = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblRockCost.setGeometry(QtCore.QRect(530, 180, 60, 16))
        self.lblRockCost.setObjectName("lblRockCost")
        self.lblPilatesCost = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblPilatesCost.setGeometry(QtCore.QRect(530, 210, 60, 16))
        self.lblPilatesCost.setObjectName("lblPilatesCost")
        self.txtCost = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtCost.setGeometry(QtCore.QRect(540, 350, 113, 21))
        self.txtCost.setReadOnly(True)
        self.txtCost.setObjectName("txtCost")
        self.lblTotalCost = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTotalCost.setGeometry(QtCore.QRect(490, 350, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lblTotalCost.setFont(font)
        self.lblTotalCost.setObjectName("lblTotalCost")
        self.btnConfirm = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnConfirm.setGeometry(QtCore.QRect(390, 270, 161, 32))
        self.btnConfirm.setObjectName("btnConfirm")
        gymGlobal.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=gymGlobal)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 43))
        self.menubar.setObjectName("menubar")
        gymGlobal.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=gymGlobal)
        self.statusbar.setObjectName("statusbar")
        gymGlobal.setStatusBar(self.statusbar)

        self.retranslateUi(gymGlobal)
        QtCore.QMetaObject.connectSlotsByName(gymGlobal)

        self.btnConfirm.clicked.connect(self.calculateTotal)

    def retranslateUi(self, gymGlobal):
        _translate = QtCore.QCoreApplication.translate
        gymGlobal.setWindowTitle(_translate("gymGlobal", "Main"))
        self.gymTitle.setText(_translate("gymGlobal", "Gym Global"))
        self.lblYoga.setText(_translate("gymGlobal", "Number of Yoga Classes"))
        self.lblRock.setText(_translate("gymGlobal", "Number of Rock-climbing Classes"))
        self.lblPilates.setText(_translate("gymGlobal", "Number of Pilates Classes"))
        self.lblTime.setText(_translate("gymGlobal", "Time Slot"))
        self.lblYogaCost.setText(_translate("gymGlobal", "$10.00"))
        self.lblRockCost.setText(_translate("gymGlobal", "$12.00"))
        self.lblPilatesCost.setText(_translate("gymGlobal", "$15.00"))
        self.lblTotalCost.setText(_translate("gymGlobal", "Total Cost"))
        self.btnConfirm.setText(_translate("gymGlobal", "Confirm Booking"))

    def calculateTotal(self):
        # Assigns YogaClass quantity input to variable
        input_yogaQuantity = self.txtYogaClasses.text()
        # Assigns YogaClass quantity input to variable
        input_rockClimbingQuantity = self.txtRockClasses.text()
        # Assigns YogaClass quantity input to variable
        input_pilatesQuantity = self.txtPilatesClasses.text()
        # Assigns time slot input to variable
        input_timeSlot = self.txtTimeslot.text()
        # Creates a new messagebox instance
        msg = QtWidgets.QMessageBox()
        # Sets the messagebox window title
        msg.setWindowTitle("Gym Global")
        # Ensures inputs are all numeric values.
        if(input_yogaQuantity.isdigit() and input_rockClimbingQuantity.isdigit() and input_pilatesQuantity.isdigit()):
            # Input validation to cast input values to type Integer.
            input_yogaQuantity = int(input_yogaQuantity)
            input_rockClimbingQuantity = int(input_rockClimbingQuantity)
            input_pilatesQuantity = int(input_pilatesQuantity)
            total = (input_yogaQuantity * 10) + (input_rockClimbingQuantity * 12) + (input_pilatesQuantity * 15)
            if(input_timeSlot == "Morning"):
                self.txtCost.setText("$" + str(total))
            elif(input_timeSlot == "Afternoon"):
                total += 5
                self.txtCost.setText("$" + str(total))
            else:
                msg = QMessageBox()
                msg.setText("Please enter 'Morning' or 'Afternoon' in the time slot.")
                msg.exec()
                
        else: 
            # Error message if input value is not type Integer.
            msg = QMessageBox()
            msg.setText("Please enter a numeric value for the amount of each class.")
            msg.exec()
        




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    gymGlobal = QtWidgets.QMainWindow()
    ui = Ui_gymGlobal()
    ui.setupUi(gymGlobal)
    gymGlobal.show()
    sys.exit(app.exec())
