# Form implementation generated from reading ui file 'firstwindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from secondwindow import Ui_secondWindow


class Ui_firstWindow(object):
    def setupUi(self, firstWindow):
        firstWindow.setObjectName("firstWindow")
        firstWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        firstWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=firstWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblInputText = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblInputText.setGeometry(QtCore.QRect(180, 80, 121, 31))
        self.lblInputText.setObjectName("lblInputText")
        self.txtInputText = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtInputText.setGeometry(QtCore.QRect(340, 80, 113, 22))
        self.txtInputText.setObjectName("txtInputText")
        self.btnShow = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnShow.setGeometry(QtCore.QRect(340, 170, 111, 31))
        self.btnShow.setObjectName("btnShow")
        self.btnTransfer = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnTransfer.setGeometry(QtCore.QRect(340, 240, 111, 31))
        self.btnTransfer.setObjectName("btnTransfer")
        firstWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=firstWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        firstWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=firstWindow)
        self.statusbar.setObjectName("statusbar")
        firstWindow.setStatusBar(self.statusbar)

        self.retranslateUi(firstWindow)
        QtCore.QMetaObject.connectSlotsByName(firstWindow)
        
        self.btnShow.clicked.connect(self.show_application)
        self.btnTransfer.clicked.connect(self.transfer_text)
        
    def transfer_text(self):
        # Read the data from the text box in the first application
        input_text = self.txtInputText.text()
        # Set the text property of the text box/lineedit widgte of the second application
        self.secondui.txtTransferredText.setText(input_text)
    
    
    def show_application(self):
        # Create an empty Main Window
        self.window = QtWidgets.QMainWindow()
        # Create a new object from the second application
        self.secondui = Ui_secondWindow()
        # Call the setupUi function of the second application
        self.secondui.setupUi(self.window)
        # display the Window
        self.window.show()

    def retranslateUi(self, firstWindow):
        _translate = QtCore.QCoreApplication.translate
        firstWindow.setWindowTitle(_translate("firstWindow", "First Window"))
        self.lblInputText.setText(_translate("firstWindow", "Enter Text"))
        self.btnShow.setText(_translate("firstWindow", "Show Window"))
        self.btnTransfer.setText(_translate("firstWindow", "Transfer Text"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    firstWindow = QtWidgets.QMainWindow()
    ui = Ui_firstWindow()
    ui.setupUi(firstWindow)
    firstWindow.show()
    sys.exit(app.exec())