# Form implementation generated from reading ui file 'studentPerformance.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import pymysql as mdb

class Ui_studentPerformance(object):
    def setupUi(self, studentPerformance):
        studentPerformance.setObjectName("studentPerformance")
        studentPerformance.resize(794, 598)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        studentPerformance.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=studentPerformance)
        self.centralwidget.setObjectName("centralwidget")
        self.lblStudentId = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblStudentId.setGeometry(QtCore.QRect(130, 110, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lblStudentId.setFont(font)
        self.lblStudentId.setObjectName("lblStudentId")
        self.lblStudentName = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblStudentName.setGeometry(QtCore.QRect(130, 140, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lblStudentName.setFont(font)
        self.lblStudentName.setObjectName("lblStudentName")
        self.txtStudentId = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtStudentId.setGeometry(QtCore.QRect(230, 110, 113, 21))
        self.txtStudentId.setObjectName("txtStudentId")
        self.txtStudentName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtStudentName.setGeometry(QtCore.QRect(230, 140, 113, 21))
        self.txtStudentName.setObjectName("txtStudentName")
        self.lblStudentAge = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblStudentAge.setGeometry(QtCore.QRect(130, 170, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lblStudentAge.setFont(font)
        self.lblStudentAge.setObjectName("lblStudentAge")
        self.txtStudentAge = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtStudentAge.setGeometry(QtCore.QRect(230, 170, 113, 21))
        self.txtStudentAge.setObjectName("txtStudentAge")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 200, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.txtStudentScore = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtStudentScore.setGeometry(QtCore.QRect(230, 200, 113, 21))
        self.txtStudentScore.setObjectName("txtStudentScore")
        self.btnInsertData = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnInsertData.setGeometry(QtCore.QRect(230, 280, 113, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.btnInsertData.setFont(font)
        self.btnInsertData.setObjectName("btnInsertData")
        self.txtDisplayData = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtDisplayData.setGeometry(QtCore.QRect(350, 280, 113, 31))
        self.txtDisplayData.setReadOnly(True)
        self.txtDisplayData.setObjectName("txtDisplayData")
        self.listWidget = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(220, 320, 256, 151))
        self.listWidget.setObjectName("listWidget")
        studentPerformance.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=studentPerformance)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 794, 43))
        self.menubar.setObjectName("menubar")
        studentPerformance.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=studentPerformance)
        self.statusbar.setObjectName("statusbar")
        studentPerformance.setStatusBar(self.statusbar)

        self.retranslateUi(studentPerformance)
        QtCore.QMetaObject.connectSlotsByName(studentPerformance)

    def connecttodb(self):
        connectionobj = mdb.connect(host="localhost", user="studentdbuser", password="studentdbuser",
        database="studentinfodb", port=3306)
        print("Connected to the DB")
        return connectionobj

    def retranslateUi(self, studentPerformance):
        _translate = QtCore.QCoreApplication.translate
        studentPerformance.setWindowTitle(_translate("studentPerformance", "Student Performance"))
        self.lblStudentId.setText(_translate("studentPerformance", "Enter Student ID:"))
        self.lblStudentName.setText(_translate("studentPerformance", "Enter Student Name:"))
        self.lblStudentAge.setText(_translate("studentPerformance", "Enter Student Age:"))
        self.label.setText(_translate("studentPerformance", "Enter Student Score:"))
        self.btnInsertData.setText(_translate("studentPerformance", "Insert Data"))
        self.txtDisplayData.setText(_translate("studentPerformance", "Display Data"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    studentPerformance = QtWidgets.QMainWindow()
    ui = Ui_studentPerformance()
    ui.setupUi(studentPerformance)
    studentPerformance.show()
    sys.exit(app.exec())
