# Form implementation generated from reading ui file 'studentscores.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_studentScores(object):
    def setupUi(self, studentScores):
        studentScores.setObjectName("studentScores")
        studentScores.resize(1117, 850)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        studentScores.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=studentScores)
        self.centralwidget.setObjectName("centralwidget")
        self.lstScores = QtWidgets.QListWidget(parent=self.centralwidget)
        self.lstScores.setGeometry(QtCore.QRect(400, 170, 251, 221))
        self.lstScores.setObjectName("lstScores")
        self.lblScores = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblScores.setGeometry(QtCore.QRect(460, 120, 111, 16))
        self.lblScores.setObjectName("lblScores")
        self.btnCalculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCalculate.setGeometry(QtCore.QRect(460, 470, 131, 31))
        self.btnCalculate.setObjectName("btnCalculate")
        self.lblAverage = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblAverage.setGeometry(QtCore.QRect(390, 580, 131, 16))
        self.lblAverage.setObjectName("lblAverage")
        self.txtAverage = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtAverage.setGeometry(QtCore.QRect(580, 580, 113, 22))
        self.txtAverage.setReadOnly(True)
        self.txtAverage.setObjectName("txtAverage")
        studentScores.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=studentScores)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1117, 23))
        self.menubar.setObjectName("menubar")
        studentScores.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=studentScores)
        self.statusbar.setObjectName("statusbar")
        studentScores.setStatusBar(self.statusbar)

        self.retranslateUi(studentScores)
        QtCore.QMetaObject.connectSlotsByName(studentScores)
        #Create an empty dictionary to store student data
        self.student_scores_dictionary = {}
        self.load_data("studentdata.txt")
        
        self.btnCalculate.clicked.connect(self.calculate_average)
        
    
    def calculate_average(self):
        if(len(self.student_scores_dictionary) > 0):
            total = 0
            for value in self.student_scores_dictionary.values():
                total = total + value   
            average = total/len(self.student_scores_dictionary)
            self.txtAverage.setText(str(average))
        else:
            msg = QtWidgets.QMessageBox()
            msg.setWindowTitle("Student Scores")
            msg.setText("No student data in the dictionary")
            msg.exec()            
        
        
    def load_data(self, file_name):
        # Open the external file in read mode
        with open(file_name, "r") as filename:
            # iterate over each line of the file
            for line in filename:
                # split the name and score by the comma delimiter
                data = line.split(",")
                # create a key and value pair and store the data in the dictionary. 
                self.student_scores_dictionary[data[0]] = int(data[1].strip())
                # populate the list widget with name and score
                self.lstScores.addItem(f"{data[0]}   {data[1].strip()}")

    def retranslateUi(self, studentScores):
        _translate = QtCore.QCoreApplication.translate
        studentScores.setWindowTitle(_translate("studentScores", "Student Scores"))
        self.lblScores.setText(_translate("studentScores", "Student Scores"))
        self.btnCalculate.setText(_translate("studentScores", "Average score"))
        self.lblAverage.setText(_translate("studentScores", "Average score"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    studentScores = QtWidgets.QMainWindow()
    ui = Ui_studentScores()
    ui.setupUi(studentScores)
    studentScores.show()
    sys.exit(app.exec())