# Form implementation generated from reading ui file 'helloworld.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox

class Ui_helloWorld(object):
    def setupUi(self, helloWorld):
        helloWorld.setObjectName("helloWorld")
        helloWorld.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        helloWorld.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=helloWorld)
        self.centralwidget.setObjectName("centralwidget")
        self.btnClick = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnClick.setGeometry(QtCore.QRect(350, 190, 113, 32))
        self.btnClick.setObjectName("btnClick")
        helloWorld.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=helloWorld)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 43))
        self.menubar.setObjectName("menubar")
        helloWorld.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=helloWorld)
        self.statusbar.setObjectName("statusbar")
        helloWorld.setStatusBar(self.statusbar)

        self.retranslateUi(helloWorld)
        QtCore.QMetaObject.connectSlotsByName(helloWorld)

        # When the btnClick button is clicked execute the function named display

        self.btnClick.clicked.connect(self.display)

    def retranslateUi(self, helloWorld):
        _translate = QtCore.QCoreApplication.translate
        helloWorld.setWindowTitle(_translate("helloWorld", "Hello World"))
        self.btnClick.setText(_translate("helloWorld", "Click Me"))

    def display(self):
        # Create a new message bix instance
        msg = QMessageBox()
        # Set the text inside the message box to display Hello World
        msg.setText("Hello World!")
        # Execute the message box (display the message box)
        msg.exec()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    helloWorld = QtWidgets.QMainWindow()
    ui = Ui_helloWorld()
    ui.setupUi(helloWorld)
    helloWorld.show()
    sys.exit(app.exec())
