# Form implementation generated from reading ui file 'fullname.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_fullName(object):
    def setupUi(self, fullName):
        fullName.setObjectName("fullName")
        fullName.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        fullName.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=fullName)
        self.centralwidget.setObjectName("centralwidget")
        self.lblFirstName = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblFirstName.setGeometry(QtCore.QRect(170, 210, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lblFirstName.setFont(font)
        self.lblFirstName.setObjectName("lblFirstName")
        self.txtFirstName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtFirstName.setGeometry(QtCore.QRect(260, 210, 113, 21))
        self.txtFirstName.setObjectName("txtFirstName")
        self.lblLastName = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblLastName.setGeometry(QtCore.QRect(170, 240, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lblLastName.setFont(font)
        self.lblLastName.setObjectName("lblLastName")
        self.txtLastName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtLastName.setGeometry(QtCore.QRect(260, 240, 113, 21))
        self.txtLastName.setObjectName("txtLastName")
        self.btnFullName = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnFullName.setGeometry(QtCore.QRect(240, 290, 141, 41))
        self.btnFullName.setObjectName("btnFullName")
        self.lblFullName = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblFullName.setGeometry(QtCore.QRect(210, 350, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lblFullName.setFont(font)
        self.lblFullName.setObjectName("lblFullName")
        self.txtFullName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtFullName.setGeometry(QtCore.QRect(260, 350, 113, 21))
        self.txtFullName.setReadOnly(True)
        self.txtFullName.setObjectName("txtFullName")
        fullName.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=fullName)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 43))
        self.menubar.setObjectName("menubar")
        fullName.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=fullName)
        self.statusbar.setObjectName("statusbar")
        fullName.setStatusBar(self.statusbar)

        self.retranslateUi(fullName)
        QtCore.QMetaObject.connectSlotsByName(fullName)

        # When the btnFullName button is clicked, execute the function get_full_name
        self.btnFullName.clicked.connect(self.get_full_name)

    def retranslateUi(self, fullName):
        _translate = QtCore.QCoreApplication.translate
        fullName.setWindowTitle(_translate("fullName", "Full Name"))
        self.lblFirstName.setText(_translate("fullName", "Enter First Name"))
        self.lblLastName.setText(_translate("fullName", "Enter Last Name"))
        self.btnFullName.setText(_translate("fullName", "Display Full Name"))
        self.lblFullName.setText(_translate("fullName", "Full Name"))
    
    def get_full_name(self):
        # Extract first name entered by the user and store in first_name variable
        first_name = self.txtFirstName.text()
        # Extract last name entered by the user and store in last_name variable
        last_name = self.txtLastName.text()
        # Join the first and last name into one string 
        concatenated_name = first_name + " " + last_name
        # Display the concateated_name to the text box
        self.txtFullName.setText(concatenated_name)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    fullName = QtWidgets.QMainWindow()
    ui = Ui_fullName()
    ui.setupUi(fullName)
    fullName.show()
    sys.exit(app.exec())
