# Form implementation generated from reading ui file 'fruitPurchase.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_fruitPurchase(object):
    def setupUi(self, fruitPurchase):
        fruitPurchase.setObjectName("fruitPurchase")
        fruitPurchase.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        fruitPurchase.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=fruitPurchase)
        self.centralwidget.setObjectName("centralwidget")
        self.lblFruit = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblFruit.setGeometry(QtCore.QRect(160, 120, 91, 16))
        self.lblFruit.setObjectName("lblFruit")
        self.cmbFruit = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cmbFruit.setGeometry(QtCore.QRect(260, 120, 104, 26))
        self.cmbFruit.setObjectName("cmbFruit")
        self.cmbFruit.addItem("")
        self.cmbFruit.addItem("")
        self.cmbFruit.addItem("")
        self.cmbFruit.addItem("")
        self.cmbFruit.addItem("")
        self.cmbFruit.addItem("")
        self.lblQuantity = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblQuantity.setGeometry(QtCore.QRect(150, 170, 91, 16))
        self.lblQuantity.setObjectName("lblQuantity")
        self.txtQuantity = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtQuantity.setGeometry(QtCore.QRect(250, 170, 113, 21))
        self.txtQuantity.setObjectName("txtQuantity")
        self.btnCalculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCalculate.setGeometry(QtCore.QRect(250, 210, 113, 32))
        self.btnCalculate.setObjectName("btnCalculate")
        self.lblCost = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblCost.setGeometry(QtCore.QRect(160, 320, 91, 16))
        self.lblCost.setObjectName("lblCost")
        self.txtTotalCost = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtTotalCost.setGeometry(QtCore.QRect(240, 320, 113, 21))
        self.txtTotalCost.setReadOnly(True)
        self.txtTotalCost.setObjectName("txtTotalCost")
        self.lblEmpty = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblEmpty.setGeometry(QtCore.QRect(510, 120, 91, 16))
        self.lblEmpty.setText("")
        self.lblEmpty.setObjectName("lblEmpty")
        fruitPurchase.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=fruitPurchase)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 43))
        self.menubar.setObjectName("menubar")
        fruitPurchase.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=fruitPurchase)
        self.statusbar.setObjectName("statusbar")
        fruitPurchase.setStatusBar(self.statusbar)

        self.retranslateUi(fruitPurchase)
        QtCore.QMetaObject.connectSlotsByName(fruitPurchase)

        self.fruit_price = {"Apple":3.50, "Orange":3.99, "Pear":4.10, "Peach": 5.99, "Banana": 1.29}
        
        self.cmbFruit.currentIndexChanged.connect(self.display_price)


    def display_price(self):
        # Store the current selected fruit in the variable/object fruit_selection
        fruit_selection = self.cmbFruit.currentText()
        price = self.fruit_price.get(fruit_selection)
        self.lblEmpty.setText(f"$(price) per pound")


    def retranslateUi(self, fruitPurchase):
        _translate = QtCore.QCoreApplication.translate
        fruitPurchase.setWindowTitle(_translate("fruitPurchase", "MainWindow"))
        self.lblFruit.setText(_translate("fruitPurchase", "Select a fruit"))
        self.cmbFruit.setItemText(0, _translate("fruitPurchase", "Fruit Selection"))
        self.cmbFruit.setItemText(1, _translate("fruitPurchase", "Apple"))
        self.cmbFruit.setItemText(2, _translate("fruitPurchase", "Orange"))
        self.cmbFruit.setItemText(3, _translate("fruitPurchase", "Pear"))
        self.cmbFruit.setItemText(4, _translate("fruitPurchase", "Peach"))
        self.cmbFruit.setItemText(5, _translate("fruitPurchase", "Banana"))
        self.lblQuantity.setText(_translate("fruitPurchase", "Enter Quantity"))
        self.btnCalculate.setText(_translate("fruitPurchase", "Calculate Cost"))
        self.lblCost.setText(_translate("fruitPurchase", "Total Cost"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    fruitPurchase = QtWidgets.QMainWindow()
    ui = Ui_fruitPurchase()
    ui.setupUi(fruitPurchase)
    fruitPurchase.show()
    sys.exit(app.exec())
