# Form implementation generated from reading ui file 'evenorodd.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_evenOrOdd(object):
    def setupUi(self, evenOrOdd):
        evenOrOdd.setObjectName("evenOrOdd")
        evenOrOdd.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        evenOrOdd.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=evenOrOdd)
        self.centralwidget.setObjectName("centralwidget")
        self.lblInput = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblInput.setGeometry(QtCore.QRect(120, 180, 101, 16))
        self.lblInput.setObjectName("lblInput")
        self.txtInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtInput.setGeometry(QtCore.QRect(220, 180, 113, 21))
        self.txtInput.setObjectName("txtInput")
        self.btnEvaluate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnEvaluate.setGeometry(QtCore.QRect(220, 210, 113, 32))
        self.btnEvaluate.setObjectName("btnEvaluate")
        self.lblResult = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblResult.setGeometry(QtCore.QRect(160, 300, 41, 16))
        self.lblResult.setObjectName("lblResult")
        self.txtResult = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtResult.setGeometry(QtCore.QRect(210, 300, 113, 21))
        self.txtResult.setReadOnly(True)
        self.txtResult.setObjectName("txtResult")
        evenOrOdd.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=evenOrOdd)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 43))
        self.menubar.setObjectName("menubar")
        evenOrOdd.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=evenOrOdd)
        self.statusbar.setObjectName("statusbar")
        evenOrOdd.setStatusBar(self.statusbar)

        self.retranslateUi(evenOrOdd)
        QtCore.QMetaObject.connectSlotsByName(evenOrOdd)

        self.btnEvaluate.clicked.connect(self.even_or_odd)

    def retranslateUi(self, evenOrOdd):
        _translate = QtCore.QCoreApplication.translate
        evenOrOdd.setWindowTitle(_translate("evenOrOdd", "Even or Odd"))
        self.lblInput.setText(_translate("evenOrOdd", "Enter a number"))
        self.btnEvaluate.setText(_translate("evenOrOdd", "Even or Odd"))
        self.lblResult.setText(_translate("evenOrOdd", "Result"))

    def even_or_odd(self):
        input_value = self.txtInput.text()
        input_value = int(input_value)
        
        if (input_value % 2 == 0):
            self.txtResult.setText("Even")
        else:
            self.txtResult.setText("Odd")

# Is this the file being executed
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    evenOrOdd = QtWidgets.QMainWindow()
    ui = Ui_evenOrOdd()
    ui.setupUi(evenOrOdd)
    evenOrOdd.show()
    sys.exit(app.exec())
