# Form implementation generated from reading ui file 'financialplanner2.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_financialPlanner2(object):
    def setupUi(self, financialPlanner2):
        financialPlanner2.setObjectName("financialPlanner2")
        financialPlanner2.resize(1110, 844)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        financialPlanner2.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=financialPlanner2)
        self.centralwidget.setObjectName("centralwidget")
        self.lblAmount = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblAmount.setGeometry(QtCore.QRect(240, 150, 231, 31))
        self.lblAmount.setObjectName("lblAmount")
        self.txtAmount = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtAmount.setGeometry(QtCore.QRect(530, 150, 113, 22))
        self.txtAmount.setObjectName("txtAmount")
        self.lblTime = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTime.setGeometry(QtCore.QRect(240, 220, 231, 31))
        self.lblTime.setObjectName("lblTime")
        self.txtTime = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtTime.setGeometry(QtCore.QRect(530, 220, 113, 22))
        self.txtTime.setObjectName("txtTime")
        self.chkPlan = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.chkPlan.setGeometry(QtCore.QRect(530, 300, 151, 31))
        self.chkPlan.setObjectName("chkPlan")
        self.btnCalculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCalculate.setGeometry(QtCore.QRect(540, 380, 93, 28))
        self.btnCalculate.setObjectName("btnCalculate")
        self.btnClear = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnClear.setGeometry(QtCore.QRect(340, 510, 93, 28))
        self.btnClear.setObjectName("btnClear")
        self.btnExit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnExit.setGeometry(QtCore.QRect(580, 510, 93, 28))
        self.btnExit.setObjectName("btnExit")
        self.lstOutput = QtWidgets.QListWidget(parent=self.centralwidget)
        self.lstOutput.setGeometry(QtCore.QRect(770, 190, 256, 341))
        self.lstOutput.setObjectName("lstOutput")
        self.lblOutput = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblOutput.setGeometry(QtCore.QRect(800, 130, 181, 31))
        self.lblOutput.setObjectName("lblOutput")
        financialPlanner2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=financialPlanner2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1110, 23))
        self.menubar.setObjectName("menubar")
        financialPlanner2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=financialPlanner2)
        self.statusbar.setObjectName("statusbar")
        financialPlanner2.setStatusBar(self.statusbar)

        self.retranslateUi(financialPlanner2)
        QtCore.QMetaObject.connectSlotsByName(financialPlanner2)
        
        # When the calculate button is clicked, execute the calculate function
        self.btnCalculate.clicked.connect(self.calculate)
        self.btnClear.clicked.connect(self.clear)
        self.btnExit.clicked.connect(self.appexit)

    def retranslateUi(self, financialPlanner2):
        _translate = QtCore.QCoreApplication.translate
        financialPlanner2.setWindowTitle(_translate("financialPlanner2", "Financial Planner"))
        self.lblAmount.setText(_translate("financialPlanner2", "Enter yearly investment amount"))
        self.lblTime.setText(_translate("financialPlanner2", "Enter number of years to invest"))
        self.chkPlan.setText(_translate("financialPlanner2", "Higher Risk Plan"))
        self.btnCalculate.setText(_translate("financialPlanner2", "Calculate"))
        self.btnClear.setText(_translate("financialPlanner2", "Clear"))
        self.btnExit.setText(_translate("financialPlanner2", "Exit"))
        self.lblOutput.setText(_translate("financialPlanner2", "Yearly portfolio amount"))
        
    def clear(self):
        #Clear the yearly amount text box
        self.txtAmount.clear()
        #Clear the time text box
        self.txtTime.clear()
        #Clear the checkbox
        self.chkPlan.setChecked(False)
        #Clear the list widget
        self.lstOutput.clear()
        
    def appexit(self):
        # Exit the application
        QtWidgets.QApplication.quit()
        
    def calculate(self):
        #To do: Add input validation
        yearly_amount = int(self.txtAmount.text())
        time_to_invest = int(self.txtTime.text())
        
        # Check if the chech box is selected
        if(self.chkPlan.isChecked()):
            rate = 7.0
        else:
            rate = 5.0
            
        current_amount = 0
        
        for year in range(1,time_to_invest+1):
            current_amount = (current_amount + yearly_amount)*(1 + rate/100)
            self.lstOutput.addItem(str(year)+ "  " + str(f"${current_amount:.2f}"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    financialPlanner2 = QtWidgets.QMainWindow()
    ui = Ui_financialPlanner2()
    ui.setupUi(financialPlanner2)
    financialPlanner2.show()
    sys.exit(app.exec())