# Form implementation generated from reading ui file 'dashboard.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from purchase import Ui_secondWindowPurchase
from display import Ui_displayWindow
from search import Ui_searchWindow

class Ui_mainWindowDashboard(object):
    def setupUi(self, mainWindowDashboard):
        mainWindowDashboard.setObjectName("mainWindowDashboard")
        mainWindowDashboard.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        mainWindowDashboard.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=mainWindowDashboard)
        self.centralwidget.setObjectName("centralwidget")
        self.txtCustomerName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtCustomerName.setGeometry(QtCore.QRect(272, 140, 161, 21))
        self.txtCustomerName.setObjectName("txtCustomerName")
        self.lblCustomerName = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblCustomerName.setGeometry(QtCore.QRect(180, 140, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lblCustomerName.setFont(font)
        self.lblCustomerName.setObjectName("lblCustomerName")
        self.btnPurchase = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnPurchase.setGeometry(QtCore.QRect(590, 90, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.btnPurchase.setFont(font)
        self.btnPurchase.setObjectName("btnPurchase")
        self.btnSearch = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSearch.setGeometry(QtCore.QRect(590, 120, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.btnSearch.setFont(font)
        self.btnSearch.setObjectName("btnSearch")
        self.btnDisplay = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDisplay.setGeometry(QtCore.QRect(590, 150, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.btnDisplay.setFont(font)
        self.btnDisplay.setObjectName("btnDisplay")
        self.btnExit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnExit.setGeometry(QtCore.QRect(590, 240, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.btnExit.setFont(font)
        self.btnExit.setObjectName("btnExit")
        mainWindowDashboard.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=mainWindowDashboard)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 43))
        self.menubar.setObjectName("menubar")
        mainWindowDashboard.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=mainWindowDashboard)
        self.statusbar.setObjectName("statusbar")
        mainWindowDashboard.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindowDashboard)
        QtCore.QMetaObject.connectSlotsByName(mainWindowDashboard)

        # Displays the display window when clicked.
        self.btnDisplay.clicked.connect(self.show_display_window)
        # Displays the search window when clicked.
        self.btnSearch.clicked.connect(self.show_search_window)
        # Displays the purchase window when clicked.
        self.btnPurchase.clicked.connect(self.show_purchase_window)
        # Exits the application when clicked.
        self.btnExit.clicked.connect(self.close_application)

    # Assigns customer name to variable. Method can be used to access customer
    # name in other classes.
    def customer_name_transfer_text(self):
        # Read the data from the text box in the first application
        customer_name = self.txtCustomerName.text()
        # Set the text property of the text box/lineedit widgte of the second application
        self.purchaseui.txtCustomerName.setText(customer_name)

    # Function to display the display window.
    def show_display_window(self):
        # Creates an empty Main Window.
        self.window = QtWidgets.QMainWindow()
        # Creates an object for the display application.
        self.displayui = Ui_displayWindow()
        # Calls the setupUi function of the display application.
        self.displayui.setupUi(self.window)
        # Displays the display window.
        self.window.show()

    # Function to display the search window.
    def show_search_window(self):
        # Creates an empty Main Window.
        self.window = QtWidgets.QMainWindow()
        # Creates an object for the display application.
        self.searchui = Ui_searchWindow()
        # Calls the setupUi function of the display application.
        self.searchui.setupUi(self.window)
        # Displays the display window.
        self.window.show()
    
    # Function to display the purchase window.
    def show_purchase_window(self):
        # Creates an empty Main Window.
        self.window = QtWidgets.QMainWindow()
        # Creates an object for the display application.
        self.purchaseui = Ui_secondWindowPurchase()
        # Calls the setupUi function of the display application.
        self.purchaseui.setupUi(self.window)
        # Transfers the customer name to purchase window.
        self.customer_name_transfer_text()
        # Displays the display window.
        self.window.show()

    # Function to close the application.
    def close_application(self):
        # Closes the application.
        sys.exit()

    def retranslateUi(self, mainWindowDashboard):
        _translate = QtCore.QCoreApplication.translate
        mainWindowDashboard.setWindowTitle(_translate("mainWindowDashboard", "Dashboard"))
        self.lblCustomerName.setText(_translate("mainWindowDashboard", "Enter Customer Name:"))
        self.btnPurchase.setText(_translate("mainWindowDashboard", "Purchase"))
        self.btnSearch.setText(_translate("mainWindowDashboard", "Search"))
        self.btnDisplay.setText(_translate("mainWindowDashboard", "Display"))
        self.btnExit.setText(_translate("mainWindowDashboard", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindowDashboard = QtWidgets.QMainWindow()
    ui = Ui_mainWindowDashboard()
    ui.setupUi(mainWindowDashboard)
    mainWindowDashboard.show()
    sys.exit(app.exec())
