# Form implementation generated from reading ui file 'dbconnectiontest.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import pymysql as mdb


class Ui_dbConnectionTest(object):
    def setupUi(self, dbConnectionTest):
        dbConnectionTest.setObjectName("dbConnectionTest")
        dbConnectionTest.resize(1118, 850)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        dbConnectionTest.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=dbConnectionTest)
        self.centralwidget.setObjectName("centralwidget")
        self.btnConnect = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnConnect.setGeometry(QtCore.QRect(470, 300, 161, 31))
        self.btnConnect.setObjectName("btnConnect")
        dbConnectionTest.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=dbConnectionTest)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1118, 23))
        self.menubar.setObjectName("menubar")
        dbConnectionTest.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=dbConnectionTest)
        self.statusbar.setObjectName("statusbar")
        dbConnectionTest.setStatusBar(self.statusbar)

        self.retranslateUi(dbConnectionTest)
        QtCore.QMetaObject.connectSlotsByName(dbConnectionTest)
        
        self.btnConnect.clicked.connect(self.db_connection)
        
    def db_connection(self):
        try:
            connectionobj = mdb.connect(host="localhost", user="testuser", password="testuser", database="student", port=3306)
            if(connectionobj):
                msg = QtWidgets.QMessageBox()
                msg.setWindowTitle("DB Connection")
                msg.setText("Connection Successfull")
                msg.exec()
        except Exception as e:
            print(e)
            print(type(e))
        finally:
            if(connectionobj):
                connectionobj.close()

    def retranslateUi(self, dbConnectionTest):
        _translate = QtCore.QCoreApplication.translate
        dbConnectionTest.setWindowTitle(_translate("dbConnectionTest", "DB Connection Test"))
        self.btnConnect.setText(_translate("dbConnectionTest", "Test DB Connection"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dbConnectionTest = QtWidgets.QMainWindow()
    ui = Ui_dbConnectionTest()
    ui.setupUi(dbConnectionTest)
    dbConnectionTest.show()
    sys.exit(app.exec())