# Form implementation generated from reading ui file 'streetFighter.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

class Player:

    def __init__(self, player_power, player_speed, player_agility):
        self.power = player_power
        self.speed = player_speed
        self.agility = player_agility
    
    def modify_stats(self, player_power, player_speed, player_agility):
        self.power = player_power
        self.speed = player_speed
        self.agility = player_agility

class Ui_streetFighter(object):
    def setupUi(self, streetFighter):
        streetFighter.setObjectName("streetFighter")
        streetFighter.resize(813, 622)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        streetFighter.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=streetFighter)
        self.centralwidget.setObjectName("centralwidget")
        self.tbStreetFighter = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tbStreetFighter.setGeometry(QtCore.QRect(50, 10, 331, 441))
        self.tbStreetFighter.setObjectName("tbStreetFighter")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.txtName = QtWidgets.QLineEdit(parent=self.tab)
        self.txtName.setGeometry(QtCore.QRect(100, 20, 113, 21))
        self.txtName.setObjectName("txtName")
        self.lblName = QtWidgets.QLabel(parent=self.tab)
        self.lblName.setGeometry(QtCore.QRect(10, 20, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lblName.setFont(font)
        self.lblName.setObjectName("lblName")
        self.lblPower = QtWidgets.QLabel(parent=self.tab)
        self.lblPower.setGeometry(QtCore.QRect(10, 70, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lblPower.setFont(font)
        self.lblPower.setObjectName("lblPower")
        self.txtPower = QtWidgets.QLineEdit(parent=self.tab)
        self.txtPower.setGeometry(QtCore.QRect(100, 70, 113, 21))
        self.txtPower.setObjectName("txtPower")
        self.lblSpeed = QtWidgets.QLabel(parent=self.tab)
        self.lblSpeed.setGeometry(QtCore.QRect(10, 120, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lblSpeed.setFont(font)
        self.lblSpeed.setObjectName("lblSpeed")
        self.txtSpeed = QtWidgets.QLineEdit(parent=self.tab)
        self.txtSpeed.setGeometry(QtCore.QRect(100, 120, 113, 21))
        self.txtSpeed.setObjectName("txtSpeed")
        self.lblAgility = QtWidgets.QLabel(parent=self.tab)
        self.lblAgility.setGeometry(QtCore.QRect(10, 170, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lblAgility.setFont(font)
        self.lblAgility.setObjectName("lblAgility")
        self.txtAgility = QtWidgets.QLineEdit(parent=self.tab)
        self.txtAgility.setGeometry(QtCore.QRect(100, 170, 113, 21))
        self.txtAgility.setObjectName("txtAgility")
        self.btnCreate = QtWidgets.QPushButton(parent=self.tab)
        self.btnCreate.setGeometry(QtCore.QRect(100, 250, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.btnCreate.setFont(font)
        self.btnCreate.setObjectName("btnCreate")
        self.tbStreetFighter.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.listPlayers = QtWidgets.QListWidget(parent=self.tab_2)
        self.listPlayers.setGeometry(QtCore.QRect(30, 90, 256, 192))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.listPlayers.setFont(font)
        self.listPlayers.setObjectName("listPlayers")
        self.lblCreatedPlayers = QtWidgets.QLabel(parent=self.tab_2)
        self.lblCreatedPlayers.setGeometry(QtCore.QRect(100, 60, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lblCreatedPlayers.setFont(font)
        self.lblCreatedPlayers.setObjectName("lblCreatedPlayers")
        self.lblModifiedPower = QtWidgets.QLabel(parent=self.tab_2)
        self.lblModifiedPower.setGeometry(QtCore.QRect(20, 300, 60, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lblModifiedPower.setFont(font)
        self.lblModifiedPower.setObjectName("lblModifiedPower")
        self.txtModifiedPower = QtWidgets.QLineEdit(parent=self.tab_2)
        self.txtModifiedPower.setGeometry(QtCore.QRect(80, 300, 113, 21))
        self.txtModifiedPower.setObjectName("txtModifiedPower")
        self.lblModifiedSpeed = QtWidgets.QLabel(parent=self.tab_2)
        self.lblModifiedSpeed.setGeometry(QtCore.QRect(20, 330, 60, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lblModifiedSpeed.setFont(font)
        self.lblModifiedSpeed.setObjectName("lblModifiedSpeed")
        self.txtModifiedSpeed = QtWidgets.QLineEdit(parent=self.tab_2)
        self.txtModifiedSpeed.setGeometry(QtCore.QRect(80, 330, 113, 21))
        self.txtModifiedSpeed.setObjectName("txtModifiedSpeed")
        self.lblModifiedAgility = QtWidgets.QLabel(parent=self.tab_2)
        self.lblModifiedAgility.setGeometry(QtCore.QRect(20, 360, 60, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lblModifiedAgility.setFont(font)
        self.lblModifiedAgility.setObjectName("lblModifiedAgility")
        self.txtModifiedAgility = QtWidgets.QLineEdit(parent=self.tab_2)
        self.txtModifiedAgility.setGeometry(QtCore.QRect(80, 360, 113, 21))
        self.txtModifiedAgility.setObjectName("txtModifiedAgility")
        self.btnModify = QtWidgets.QPushButton(parent=self.tab_2)
        self.btnModify.setGeometry(QtCore.QRect(200, 350, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.btnModify.setFont(font)
        self.btnModify.setObjectName("btnModify")
        self.tbStreetFighter.addTab(self.tab_2, "")
        streetFighter.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=streetFighter)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 813, 43))
        self.menubar.setObjectName("menubar")
        streetFighter.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=streetFighter)
        self.statusbar.setObjectName("statusbar")
        streetFighter.setStatusBar(self.statusbar)

        self.retranslateUi(streetFighter)
        self.tbStreetFighter.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(streetFighter)

        # Creating an empty dictionary to store players
        self.created_players = { }

        self.btnCreate.clicked.connect(self.create_player)

        self.listPlayers.itemClicked.connect(self.display_stats)

        self.btnModify.clicked.connect(self.modify_player)

        #To do
        #1) Input Validation.
        #2) Exception handling.
        #3) Message boxes.
        #4) Add comments.

    def modify_player(self):
        player_name = self.listPlayers.currentItem().text()
        player_object = self.created_players.get(player_name)
        modified_power = self.txtModifiedPower.text()
        modified_speed = self.txtModifiedSpeed.text()
        modified_agility = self.txtModifiedAgility.text()
    
        player_object.modify_stats(modified_power, modified_speed, modified_agility)    

    def display_stats(self):
        player_name = self.listPlayers.currentItem().text()
        player_object = self.created_players.get(player_name)
        self.txtModifiedPower.setText(player_object.power)
        self.txtModifiedSpeed.setText(player_object.speed)
        self.txtModifiedAgility.setText(player_object.agility)

    def create_player(self):
        player_name = self.txtName.text()
        player_power = self.txtPower.text()
        player_speed = self.txtSpeed.text()
        player_agility = self.txtAgility.text()
        # Player object creation
        player_object = Player(player_power, player_speed, player_agility)
        # Storing the player object in the dictionary
        self.created_players[player_name] = player_object
        self.listPlayers.addItem(player_name)

    def retranslateUi(self, streetFighter):
        _translate = QtCore.QCoreApplication.translate
        streetFighter.setWindowTitle(_translate("streetFighter", "Street Fighter"))
        self.lblName.setText(_translate("streetFighter", "Enter Player Name:"))
        self.lblPower.setText(_translate("streetFighter", "Enter Player Power:"))
        self.lblSpeed.setText(_translate("streetFighter", "Enter Player Speed:"))
        self.lblAgility.setText(_translate("streetFighter", "Enter Player Agility:"))
        self.btnCreate.setText(_translate("streetFighter", "Create Player"))
        self.tbStreetFighter.setTabText(self.tbStreetFighter.indexOf(self.tab), _translate("streetFighter", "Create Player"))
        self.lblCreatedPlayers.setText(_translate("streetFighter", "List of Created Players"))
        self.lblModifiedPower.setText(_translate("streetFighter", "Player Power:"))
        self.lblModifiedSpeed.setText(_translate("streetFighter", "Player Speed:"))
        self.lblModifiedAgility.setText(_translate("streetFighter", "Player Agility:"))
        self.btnModify.setText(_translate("streetFighter", "Save Modifications"))
        self.tbStreetFighter.setTabText(self.tbStreetFighter.indexOf(self.tab_2), _translate("streetFighter", "Modify Player"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    streetFighter = QtWidgets.QMainWindow()
    ui = Ui_streetFighter()
    ui.setupUi(streetFighter)
    streetFighter.show()
    sys.exit(app.exec())
